version: "2.2"
services:
  db:
    build: ./core/support/virtuoso
    container_name: pheno-virtuoso
    environment:
      DBA_PASSWORD: "dba"
      SPARQL_UPDATE: "true"
      SPARQL_LOAD_SERVICE_DATA: "true"
      DEFAULT_GRAPH: "http://phenomebrowser.net"
    volumes:
      - ./core/support/virtuoso/data/virtuoso:/data
    ports:
      - "8890:8890"
      - "1111:1111"
    networks:
      - esnet
    restart: unless-stopped
  phenotype-reactor-ui:
    build: ./phenotype-reactor-ui
    container_name: phenotype-reactor-ui
    ports:
      - 80:80
      - 443:443
    networks:
      - esnet
    depends_on: 
      - db
    restart: unless-stopped
networks:
  esnet:
