version: "3.3"
services:
  db:
    build: .
    container_name: pheno-virtuoso
    environment:
      DBA_PASSWORD: "dba"
      SPARQL_UPDATE: "true"
      SPARQL_LOAD_SERVICE_DATA: "true"
      DEFAULT_GRAPH: "http://ddiem.phenomebrowser.net"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:8890"
      - "1111:1111"